Update window.location mocks to use Object.defineProperty
Following the Jest update to use JSDOM v16, update window.location mocks
to use `Object.defineProperty` to get past this error:

```
TypeError: Cannot assign to read only property 'assign' of object '[object Location]'
```